apiVersion: v1
kind: Secret
metadata:
  name: activemq-secret
type: Opaque
data:
  jetty-realm.properties: IyBEZWZpbmVzIHVzZXJzIHRoYXQgY2FuIGFjY2VzcyB0aGUgd2ViIChjb25zb2xlLCBkZW1vLCBldGMuKQojIHVzZXJuYW1lOiBwYXNzd29yZCBbLHJvbGVuYW1lIC4uLl0KYWN0aXZlbXEtYWRtaW46IHcjNyRrXlBtSWIwR15Vb0JaSVNeT2dCTjRTemlhaiwgYWRtaW4=